name: pizzapal
description: "PizzaPal is a Flutter-based iOS app designed to enhance your pizza ordering experience. This app supports full CRUD operations, allowing users to create, read, update, and delete their pizza orders with ease. Features include a user-friendly interface, customizable pizza options, and real-time order tracking. Built to provide a seamless and interactive experience, PizzaPal aims to be your ultimate pizza companion, ensuring every slice is just a tap away"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg_provider: ^1.0.7
  re_svg: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: ^2.0.10+1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
